name: Frontend License & Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan_frontend:
    name: Scan Frontend Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: Install Project Dependencies
      #   run: npm install

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Install ScanCode Dependencies
      #   run: |
      #     sudo apt-get update && sudo apt-get upgrade -y
      #     sudo apt install -y bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0

      - name: Download and Extract ScanCode Toolkit v32.0.8
        run: |
          wget https://github.com/aboutcode-org/scancode-toolkit/releases/download/v32.0.8/scancode-toolkit-v32.0.8_py3.10-linux.tar.gz
          tar -xzf scancode-toolkit-v32.0.8_py3.10-linux.tar.gz
          mv scancode-toolkit-v32.0.8 scancode-toolkit
          chmod +x scancode-toolkit/scancode
          chmod +x scancode-toolkit/configure

      - name: Configure ScanCode Toolkit
        run: |
          cd scancode-toolkit
          ./configure

      - name: Verify Python Version
        run: python --version

      - name: Run ScanCode on Frontend
        run: |
          cd scancode-toolkit
          scancode --json scancode-results.json Frontend/

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: scancode-results
          path: scancode-results.json

      - name: Check Scan Results for Issues
        run: |
          if grep -q '"errors": \[' scancode-results.json; then
            echo "License or security issues detected in dependencies!"
            exit 1
          fi
